export default {
    data: {
        //      I M A G E S
        bg: "/common/images/bg.png",
        wifi: "/common/images/wifi.png",
        apps: "/common/images/apps.png",
        lock: "/common/images/lock.png",
        location: '/common/images/location.png',
        weather: '/common/images/weather.png',
        scroll_inactive: '/common/images/scroll_inactive.png',
        time_bg: "/common/images/time_bg.png",
        music_bg: "/common/images/music_bg.png",
        storage_bg: "/common/images/storage_bg.png",
        tap_to_speak_bg: "/common/images/tap_to_speak_bg.png",
        refrigerator_doors_bg: "/common/images/refrigerator_doors_bg.png",
        recepie_bg: "/common/images/recepie_bg.png",
        bottom_tab_bg: "/common/images/bottom_tab_bg.png",
        dreams_img: '/common/images/dreams_img.png',
        shuffle: '/common/images/shuffle.png',
        back: '/common/images/back.png',
        play: '/common/images/play.png',
        next: '/common/images/next.png',
        range: '/common/images/range.png',
//      : '/common/images/.png',
        vegetables_range_white: '/common/images/vegetables_range_white.png',
        green_range: '/common/images/green_range.png',
        orange_range: '/common/images/orange_range.png',
        violet_range: '/common/images/violet_range.png',
        microphone: '/common/images/microphone.png',
        recp_1: '/common/images/vada.png',
        recp_2: '/common/images/meals.png',
        recp_3: '/common/images/dosa.png',
        clock: '/common/images/clock.png',
        favourite_active: '/common/images/favourite_active.png',
        favourite_inactive: '/common/images/favourite_inactive.png',
        home_icon: '/common/images/home.png',
        storage_icon: '/common/images/storage.png',
        music_icon: '/common/images/music.png',
        settings_icon: '/common/images/settings.png',
        view_icon: '/common/images/view_icon.png',
        add_icon: '/common/images/add_icon.png',
        st_item_1: '/common/images/chicken.png',
        st_item_2: '/common/images/vegetables.png',
        st_item_3: '/common/images/spinach.png',
        st_item_4: '/common/images/fruits.png',
        st_item_5: '/common/images/fruits.png',
        pink_button: '/common/images/pink_button.png',

        //      T E X T
        username: 'UserName',
        time: '10:00 PM',
        loaction_city:"Bangalore",
        day_date:"Wednesday, 17 Dec",
        temp_red:"30°",
        storage_settings:'Storage Settings',
        dinner_text:'Dinner Recepies for you',
        all_recp_text:'All Recepies',
        song_name: 'Dreams',
        song_genre: 'Romantic',
        food_remain: 'Food Remaining',
        home_txt: "Home",
        storage_txt: "Storage",
        music_txt: "Music",
        settings_txt: "Settings",
        audio_assist1:"How can I help you?",
        audio_assist2:"Tap to Speak",
        your_storage:"Your Storage",
        view_text:"View",
        add_text:"Add",
        st_item_1_name:"Fresh Chicken",
        st_item_2_name:"Vegetables",
        st_item_3_name:"Spinach",
        st_item_4_name:"Fruits",
        st_item_5_name:"Milk",
        st_item_1_weight:"1kg",
        st_item_2_weight:"3kg",
        st_item_3_weight:"500g",
        st_item_4_weight:"3kg",
        st_item_5_weight:"2lts",
        door_text:"Refrigerator Doors",
        door_status:"Locked",
        door_status_toggle:"Unlock",
        superfreeze_toggle_txt:"Off",
        bottom_box_left_toggle_text: "Freeze",
        bottom_box_right_toggle_text: "Fresh",
        crisp_fresh_text:"Off",




    },


}
